#!/bin/bash

for file in $(find . *.jpg); do

  file_name=$(basename $file)


date=${file_name:10:4}-${file_name:14:2}-${file_name:16:2}
time=${file_name:19:2}:${file_name:21:2}:${file_name:23:2}

echo $file
echo $file_name


convert $file -pointsize 36 -fill red -annotate +22+1920 "$date $time" $file


done


