#!/bin/bash

##look for all jpg files less than 120 minutes old
for file in $(find . -mmin -120); do

#Strip off leading directory information and create a new variable
file_name=$(basename $file)

#Create a variable for the date using filename slicing.
date=${file_name:11:4}-${file_name:15:2}-${file_name:17:2}

#Create a variable for the time using filename slicing.
time=${file_name:20:2}:${file_name:22:2}:${file_name:24:2}

#Print out the name of the file to be processed
echo timestamping $file_name

#Use convert to add the date and time to the image. This will be in the format YYYY-MM-DD TT:TT
convert $file -pointsize 36 -fill red -annotate +22+1920 "$date $time" $file

#Count the number of processes running called convert and limit it to 50
 i=`ps aux |grep convert |wc -l`
       until [ $i -lt 50 ]; do
                i=`ps aux |grep convert |wc -l`
                echo $i   

        done


done


